[2024-06-01T03:24:23.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T03:24:23.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:18:16.454131+00:00 [queued]>
[2024-06-01T03:24:23.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:18:16.454131+00:00 [queued]>
[2024-06-01T03:24:23.461+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-01T03:24:23.466+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): domain_analysis> on 2024-06-01 03:18:16.454131+00:00
[2024-06-01T03:24:23.468+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T03:24:23.468+0000] {standard_task_runner.py:63} INFO - Started process 248 to run task
[2024-06-01T03:24:23.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'domain_analysis', 'manual__2024-06-01T03:18:16.454131+00:00', '--job-id', '3675', '--raw', '--subdir', 'DAGS_FOLDER/soc_dag.py', '--cfg-path', '/tmp/tmppj13plkd']
[2024-06-01T03:24:23.469+0000] {standard_task_runner.py:91} INFO - Job 3675: Subtask domain_analysis
[2024-06-01T03:24:23.475+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T03:24:23.488+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.domain_analysis manual__2024-06-01T03:18:16.454131+00:00 [running]> on host e11ec26ff801
[2024-06-01T03:24:23.521+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='domain_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T03:18:16.454131+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T03:18:16.454131+00:00'
[2024-06-01T03:24:23.522+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T03:24:23.532+0000] {soc_dag.py:28} INFO - Starting to fetch soc
[2024-06-01T03:24:23.532+0000] {soc_dag.py:35} ERROR - Error fetching domains: module 'whois' has no attribute 'whois'
[2024-06-01T03:24:23.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T03:24:23.532+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/soc_dag.py", line 29, in domain_analysis
    result = DomainAnalysisOperator.query_domain("google.com")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 167, in query_domain
    domain_creation_date = DomainAnalysisOperator.get_domain_creation_date(domain)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 56, in get_domain_creation_date
    domain_info = whois.whois(domain)
                  ^^^^^^^^^^^
AttributeError: module 'whois' has no attribute 'whois'
[2024-06-01T03:24:23.537+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=soc_domain_analysis, task_id=domain_analysis, run_id=manual__2024-06-01T03:18:16.454131+00:00, execution_date=20240601T031816, start_date=20240601T032423, end_date=20240601T032423
[2024-06-01T03:24:23.541+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3675 for task domain_analysis (module 'whois' has no attribute 'whois'; 248)
[2024-06-01T03:24:23.567+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T03:24:23.574+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T03:24:23.574+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
