[2024-06-01T06:38:03.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T06:38:03.419+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-01T08:00:00+00:00 [queued]>
[2024-06-01T06:38:03.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-01T08:00:00+00:00 [queued]>
[2024-06-01T06:38:03.421+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-01T06:38:03.425+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_analyze_persist_task> on 2023-01-01 08:00:00+00:00
[2024-06-01T06:38:03.428+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T06:38:03.428+0000] {standard_task_runner.py:63} INFO - Started process 1197 to run task
[2024-06-01T06:38:03.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis_procedural', 'fetch_analyze_persist_task', 'scheduled__2023-01-01T08:00:00+00:00', '--job-id', '3761', '--raw', '--subdir', 'DAGS_FOLDER/asset_analysis_procedural.py', '--cfg-path', '/tmp/tmp455udmu_']
[2024-06-01T06:38:03.429+0000] {standard_task_runner.py:91} INFO - Job 3761: Subtask fetch_analyze_persist_task
[2024-06-01T06:38:03.435+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T06:38:03.448+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis_procedural.fetch_analyze_persist_task scheduled__2023-01-01T08:00:00+00:00 [running]> on host 328411755fd7
[2024-06-01T06:38:03.478+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis_procedural' AIRFLOW_CTX_TASK_ID='fetch_analyze_persist_task' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T08:00:00+00:00'
[2024-06-01T06:38:03.478+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T06:38:03.482+0000] {asset_analysis_procedural.py:27} INFO - Starting to fetch domains
[2024-06-01T06:38:03.499+0000] {asset_analysis_procedural.py:43} INFO - Fetched domains
[2024-06-01T06:38:03.500+0000] {asset_analysis_procedural.py:47} INFO - Analyzing domain: goggle.com with original domain: google.com
[2024-06-01T06:38:04.467+0000] {asset_analysis_procedural.py:50} INFO - Persisting domain analysis for: goggle.com
[2024-06-01T06:38:04.471+0000] {asset_analysis_procedural.py:76} ERROR - Error fetching, analyzing, or persisting domains: name 'url' is not defined
[2024-06-01T06:38:04.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T06:38:04.472+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asset_analysis_procedural.py", line 63, in fetch_analyze_persist_domains
    logging.info(f"Persisting URL analysis for: {url}")
                                                 ^^^
NameError: name 'url' is not defined
[2024-06-01T06:38:04.484+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=soc_domain_analysis_procedural, task_id=fetch_analyze_persist_task, run_id=scheduled__2023-01-01T08:00:00+00:00, execution_date=20230101T080000, start_date=20240601T063803, end_date=20240601T063804
[2024-06-01T06:38:04.491+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3761 for task fetch_analyze_persist_task (name 'url' is not defined; 1197)
[2024-06-01T06:38:04.520+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T06:38:04.530+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T06:38:04.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
