[2024-06-01T05:59:51.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T05:59:51.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.persist_domain_analysis_task manual__2024-06-01T05:17:51.040496+00:00 [queued]>
[2024-06-01T05:59:51.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.persist_domain_analysis_task manual__2024-06-01T05:17:51.040496+00:00 [queued]>
[2024-06-01T05:59:51.758+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-01T05:59:51.762+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): persist_domain_analysis_task> on 2024-06-01 05:17:51.040496+00:00
[2024-06-01T05:59:51.765+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3535) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T05:59:51.766+0000] {standard_task_runner.py:63} INFO - Started process 3536 to run task
[2024-06-01T05:59:51.765+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'persist_domain_analysis_task', 'manual__2024-06-01T05:17:51.040496+00:00', '--job-id', '3736', '--raw', '--subdir', 'DAGS_FOLDER/asset_analysis.py', '--cfg-path', '/tmp/tmp2oabg3z2']
[2024-06-01T05:59:51.766+0000] {standard_task_runner.py:91} INFO - Job 3736: Subtask persist_domain_analysis_task
[2024-06-01T05:59:51.772+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T05:59:51.785+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.persist_domain_analysis_task manual__2024-06-01T05:17:51.040496+00:00 [running]> on host 01982e9630cb
[2024-06-01T05:59:51.815+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='persist_domain_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T05:17:51.040496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T05:17:51.040496+00:00'
[2024-06-01T05:59:51.815+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T05:59:51.838+0000] {asset_analysis.py:90} ERROR - Error persisting domain analysis: 'NoneType' object is not iterable
[2024-06-01T05:59:51.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T05:59:51.839+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/asset_analysis.py", line 73, in persist_domain_analysis
    for result in analysis_results:
TypeError: 'NoneType' object is not iterable
[2024-06-01T05:59:51.843+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=soc_domain_analysis, task_id=persist_domain_analysis_task, run_id=manual__2024-06-01T05:17:51.040496+00:00, execution_date=20240601T051751, start_date=20240601T055951, end_date=20240601T055951
[2024-06-01T05:59:51.847+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3736 for task persist_domain_analysis_task ('NoneType' object is not iterable; 3536)
[2024-06-01T05:59:51.873+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T05:59:51.879+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T05:59:51.880+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
