[2024-05-25T04:57:52.625+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T04:57:52.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T04:57:52.627+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:57:52.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:57:52.632+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:57:52.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T04:57:52.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:57:52.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.026 seconds
[2024-05-25T04:58:22.965+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:22.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T04:58:22.969+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:58:22.968+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:22.975+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:58:22.973+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T04:58:22.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:22.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.031 seconds
[2024-05-25T04:58:53.451+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:53.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T04:58:53.455+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:58:53.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:53.461+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:58:53.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T04:58:53.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:58:53.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.041 seconds
[2024-05-25T04:59:23.919+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:23.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T04:59:23.923+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:59:23.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:23.929+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:59:23.928+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T04:59:23.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:23.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.036 seconds
[2024-05-25T04:59:54.333+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:54.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T04:59:54.337+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:59:54.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:54.342+0000] {logging_mixin.py:188} INFO - [2024-05-25T04:59:54.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T04:59:54.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T04:59:54.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
[2024-05-25T05:00:24.774+0000] {processor.py:161} INFO - Started process (PID=321) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:24.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:00:24.777+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:00:24.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:24.784+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:00:24.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:00:24.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:24.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
[2024-05-25T05:00:55.176+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:55.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:00:55.180+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:00:55.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:55.190+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:00:55.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:00:55.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:00:55.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.045 seconds
[2024-05-25T05:01:25.677+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:25.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:01:25.681+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:01:25.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:25.686+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:01:25.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:01:25.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:25.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
[2024-05-25T05:01:56.177+0000] {processor.py:161} INFO - Started process (PID=381) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:56.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:01:56.180+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:01:56.179+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:56.186+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:01:56.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:01:56.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:01:56.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.032 seconds
[2024-05-25T05:02:26.611+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:26.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:02:26.614+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:02:26.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:26.618+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:02:26.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:02:26.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:26.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
[2024-05-25T05:02:54.422+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:54.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:02:54.424+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:02:54.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:54.429+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:02:54.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:02:54.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:02:54.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.024 seconds
[2024-05-25T05:03:24.786+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:24.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:03:24.790+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:03:24.789+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:24.796+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:03:24.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:03:24.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:24.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.037 seconds
[2024-05-25T05:03:55.324+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:55.325+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:03:55.327+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:03:55.327+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:55.333+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:03:55.332+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:03:55.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:03:55.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.034 seconds
[2024-05-25T05:04:25.807+0000] {processor.py:161} INFO - Started process (PID=281) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:25.809+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:04:25.811+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:04:25.811+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:25.816+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:04:25.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:04:25.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:25.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
[2024-05-25T05:04:56.267+0000] {processor.py:161} INFO - Started process (PID=301) to work on /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:56.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/soc_dag.py for tasks to queue
[2024-05-25T05:04:56.270+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:04:56.270+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:56.276+0000] {logging_mixin.py:188} INFO - [2024-05-25T05:04:56.274+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/soc_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soc_dag.py", line 2, in <module>
    from soc_script import query_domain_airflow
  File "/opt/airflow/dags/soc_script.py", line 4, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
[2024-05-25T05:04:56.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/soc_dag.py
[2024-05-25T05:04:56.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/soc_dag.py took 0.033 seconds
